### ISSUE TITLE
Implicit triggerRender

### ISSUE THREAD

**Issue by xhlulu** [plotly/dash-vtk#41]
I feel the `triggerRender` is a bit clunky and makes it impossible to have more than one callback that updates a given view. how much effort would it be to make that implicit?

EDIT: Ok so it already works with the trigger render, so let's remove it from the demos:
- [ ] usage-vtk-cfd
- [ ] slice-rendering
- [ ]

**Comment by xhlulu** [comment]
For example, the following approach would not work:
```python
@app.callback(
  [Output("vtk-view", "triggerRender"), Output("mesh", "value")],
  [Input(...)]
)
def update_mesh_nested_in_view(...):
```

**Comment by jourdain** [comment]
It is already the case... You can remove such output

**Comment by xhlulu** [comment]
@jourdain you are right. i'll update the issue as a reminder to remove those from the tutorials/demos since it's legacy.

**Comment by xhlulu** [comment]
@jourdain Actually, seems like it's not true for all cases.

With the F1 vehicle geometry app, it seems like it doesn't work when we try to set the visibility, but it only works when we update the mesh color.

Without the triggerrender:
![without-trigger](https://user-images.githubusercontent.com/21180505/114632729-4365d100-9c8d-11eb-8eec-0185ec387a44.gif)

With the trigger render:
![with-trigger](https://user-images.githubusercontent.com/21180505/114632739-4791ee80-9c8d-11eb-9450-160180e8cdb9.gif)

**Comment by jourdain** [comment]
That is an easy fix... I'll do it tomorrow

**Comment by jourdain** [comment]
react-vtk-js@1.4.3 should fix that if you update dash_vtk tomorrow morning before I start my work...

**Comment by xhlulu** [comment]
I haven't tried this but it doesn't seem to be a problem anymore. Will close it but if it comes back in the future we can reopen

**Comment by MuntherOdeh** [comment]
Hi, I've tried the code app.py but it's still not working with or without the trigger render. It gives me everytime the same error: 
Callback error updating vtk-view.triggerRender
